compile: bin
	javac -d bin -cp ./biuoop*.jar src/*.java

run2:
	java -cp ./biuoop*.jar:./bin AbstractArtDrawing

run3:
	java -cp ./biuoop*.jar:./bin BouncingBallAnimation

bin:
	mkdir bin

clean:
	rm -rf bin